config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"

  namespace :admin do
    resources :plans
  end

  resources :services, only: [:index, :edit]
  resources :notifications, only: [:index, :edit, :new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  include BaseModel
  self.abstract_class = true
end

app/models/base_model.rb
module BaseModel
  extend ActiveSupport::Concern

  class_methods do
    def table_name_prefix
      "m_" if name.first(3) == "M::"
    end
  end
end

app/models/plan.rb
class Plan < ApplicationRecord
  acts_as_paranoid

  belongs_to :product

  has_many :programs

  validates :name, presence: true
  validates :product_id, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_one :info_on_student_portal, dependent: :destroy

  has_many :plans, dependent: :destroy
  has_many :courses
  has_many :notifications
  has_many :users, through: :products_users
  has_many :products_users, dependent: :destroy

  validates :code, uniqueness: true, length: {maximum: 50}
  validates :name, presence: true, length: {maximum: 255}
end

app/models/unique_random.rb
module UniqueRandom
  private
  def unique_random attr
    str = ""
    str_len = Settings.public_send(self.class.name.underscore.pluralize)
              .public_send(attr)
              .public_send(:secure_length).to_i / 2
    loop do
      str = SecureRandom.hex str_len
      break unless self.class.exists?(attr => str)
    end
    assign_attribtes attr => str
    str
  end
end

app/controllers/admin/plans_controller.rb
class Admin::PlansController < ApplicationController
  before_action :load_plans, only: :index
  before_action :load_products, only: [:new, :edit]
  before_action :load_plan, only: [:show, :edit, :update, :destroy]

  def index; end

  def show
    respond_to(&:js)
  end

  def new
    @plan = Plan.new
    respond_to(&:js)
  end

  def create
    plan = Plan.new plan_params
    if plan.save
      flash[:success] = t "messages.create_success"
    else
      flash[:danger] = t "messages.create_fail"
    end
    redirect_to admin_plans_path
  end

  def edit
    respond_to do |format|
      format.js{render "new.js.erb"}
    end
  end

  def update
    if @plan.update_attributes plan_params
      flash[:success] = t "messages.update_success"
    else
      flash[:danger] = t "messages.update_fail"
    end
    redirect_to admin_plans_path
  end

  def destroy
    if @plan.destroy
      flash[:success] = t "messages.delete_success"
    else
      flash[:danger] = t "messages.delete_fail"
    end
    redirect_to admin_plans_path
  end

  private
  def load_products
    @products = Product.all
  end

  def load_plans
    @plans = Plan.page(params[:page]).per Settings.per_page.plan
  end

  def load_plan
    @plan = Plan.find_by id: params[:id]
    redirect_to admin_plans_path, flash: {danger: t("messages.load_data_fail")} unless @plan
  end

  def plan_params
    params.require(:plan).permit :name, :product_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  add_breadcrumb I18n.t("breadcrumbs.dashboard"), :root_path
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  add_breadcrumb I18n.t("breadcrumbs.notifications"), :notifications_path

  def index
  end

  def edit
    add_breadcrumb t "breadcrumbs.edit_notification"
  end

  def new
    add_breadcrumb t("breadcrumbs.new_notification"), :new_notification_path
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  add_breadcrumb I18n.t("breadcrumbs.services"), :services_path, class: "active"

  def index
  end

  def edit
    add_breadcrumb t "breadcrumbs.edit_service"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class path
    "active" if request.original_fullpath.include? path
  end

  def selected_plan plan
    return plan.product.id if plan.product.present?
    {}
  end

  def render_i18n_edit_create plan
    if plan.new_record?
      I18n.t("admin.btn.create")
    else
      I18n.t("admin.btn.edit")
    end
  end
end

app/views/admin/plans/_new_plan_modal.html.erb
<div class="floating_window settings modal modal-body">
  <div style="width: 800px;">
    <div class="window_bar"><%= t ".title" %><div class="window_close" onclick="hideModal(this)">×</div></div>
    <div class="data_area">
      <%= form_for [:admin, @plan] do |f| %>
        <section class="cut_sheet_area">
          <div class="clearfix button_area invalid_area">
          </div>
          <div class="errors"></div>
          <ul>
            <li>
              <%= t ".name" %>
            </li>
            <li id="length">
              <%= f.text_field :name %>
            </li>
          </ul>
          <ul>
            <li><%= t ".product.name" %></li>
            <li>
              <span class="fm_select">
                <%= f.select :product_id,
                  options_for_select(@products.collect {|p| [ p.name, p.id ] },
                  selected_plan(@plan)) %>
              </span>
            </li>
          </ul>
        </section>
        <section>
          <div class="clearfix button_area">
            <div class="btn_auto_support" id="btn_cancel"
              onclick="hideModal(this)"><%= t ".cancel" %></div>
            <%= f.submit render_i18n_edit_create(@plan), class: "btn_auto_action", id: "btn_create" %>
          </div>
        </section>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/plans/_plans.html.erb
<%= link_to new_admin_plan_path, method: :get, remote: true,
  class: "btn_fix_action btn_ico btn_ico_plus opt-mt10" do %>
  <span>新規ユーザの追加</span>
<% end %>
<section class="data_list_area mygol_user_list">
  <table>
    <thead>
      <tr>
        <th rowspan="2"><%= Plan.human_attribute_name :no %></th>
        <th rowspan="2"><%= t ".name" %></th>
        <th rowspan="2"><%= t ".product" %></th>
        <th rowspan="2"><%= t ".created_at" %></th>
        <th rowspan="2"><%= t ".updated_at" %> </th>
        <th rowspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% plans.each_with_index do |plan, index| %>
        <tr recordindex="0">
          <td class="opt-al-c"><%= index.next %></td>
          <td class="opt-al-c"><%= plan.name %></td>
          <td class="opt-al-c"><%= plan.product.name if plan.product.present? %></td>
          <td class="opt-al-c"><%= l plan.created_at, format: :format_datetime %></td>
          <td class="opt-al-c"><%= l plan.updated_at, format: :format_datetime %></td>
          <td>
            <%= link_to edit_admin_plan_path(plan), method: :get, remote: true, class: "class_link mg-link" do %>
              <font><font>Edit</font></font>
            <% end %>
            <%= link_to admin_plan_path(plan), method: :get, remote: true, class: "class_link mg-link" do %>
              <font><font>Details</font></font>
            <% end %>
            <%= link_to admin_plan_path(plan), method: :delete,
              class: "class_link mg-link", data: {confirm: t("messages.confirm")} do %>
              <font><font>Delete</font></font>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <center><%= paginate plans, theme: "twitter-bootstrap-3" %></center>
</section>

app/views/admin/plans/_show_plan_modal.html.erb
<div class="floating_window settings modal modal-body">
  <div style="width: 800px;">
    <div class="window_bar"><%= t ".title" %><div class="window_close" onclick="hideModal(this)">×</div></div>
    <div class="data_area">
      <%= form_for [:admin, @plan] do |f| %>
        <section class="cut_sheet_area">
          <div class="clearfix button_area invalid_area">
          </div>
          <div class="errors"></div>
          <ul>
            <li>
              <%= t ".name" %>
            </li>
            <li>
              <%= f.object.name %>
            </li>
          </ul>
          <ul>
            <li><%= t ".product" %></li>
            <li>
              <%= f.object.product.name if f.object.product.present? %>
            </li>
          </ul>
          <ul>
            <li><%= t ".updated_at" %></li>
            <li>
              <%= l f.object.created_at, format: :format_datetime %>
            </li>
          </ul>
          <ul>
            <li><%= t ".created_at" %></li>
            <li>
              <%= l f.object.updated_at, format: :format_datetime %>
            </li>
          </ul>
        </section>
        <section>
          <div class="clearfix button_area">
            <div class="btn_auto_support" id="btn_cancel"
              onclick="hideModal(this)"><%= t ".cancel" %></div>
          </div>
        </section>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/plans/index.html.erb
<% provide(:title, t(".title")) %>
<div class="floating_window_background modal fade" id="modalPlan"></div>
<div id="flash-message">
  <%= render "admin/shared/flash", flash: flash %>
</div>
<%= render "admin/plans/plans", plans: @plans %>

app/views/admin/plans/new.js.erb
$("#modalPlan").html("<%= j render "admin/plans/new_plan_modal" %>");
$('#modalPlan').show();

app/views/admin/plans/show.js.erb
$("#modalPlan").html("<%= j render "admin/plans/show_plan_modal" %>");
$('#modalPlan').show();

app/views/admin/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert <%= "alert-#{key}" %>">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
    <%= value unless value.blank? %>
  </div>
<% end %>

app/views/dashboard/index.html.erb
<% provide(:title, t(".title")) %>
<section>
  <!-- TODO: Dashboard content go here -->
</section>

app/views/layouts/_breadcrumb.html.erb
<ol class="breadcrumb">
  <%= render_breadcrumbs tag: :li, separator: "" %>
</ol>

app/views/layouts/_footer.html.erb
<footer class="mainFooter" role="contentinfo">
  <ul class="ft_ut">
    <li><a href="#">お問い合わせ</a></li>
    <li><a href="#">ヘルプ</a></li>
    <li><a href="#">利用規約</a></li>
    <li><a href="#">グロービス法人向け人材育成サービス</a></li>
  </ul>
  <small><span>&copy;</span><%= t ".copyright" %></small>
</footer>

app/views/layouts/_header.html.erb
<header class="mainHeader" role="banner">
  <h1 class="hd_ttl">
    <%= link_to root_path  do %>
      <img src="<%= asset_path 'hd_logo.png' %>" class="hd_lg" alt="GLOBIS">
    <% end %>
  </h1>
  <div class="hd_ut">
    <div class="hd_ut_inr">
      <span class="hd_ut_ico gold">ランク</span>
      <span class="hd_ut_name">（株）グロービス 山田 太郎 様</span>
      <a href="#" class="hd_ut_log"><%= t ".log_out" %></a>
    </div>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<nav role="navigation">
  <h2><%= t ".title" %></h2>
  <ul>
    <li class="nv_ico nv_portal">
      <a href="#" class="accordion_title"><span><%= t ".system_management" %></span></a>
      <ul class="accordion_contents">
        <li><%= link_to t(".services_management"), services_path %></li>
        <li><a href="#"><%= t ".faq_management" %></a></li>
        <li><a href="#"><%= t ".terms_management" %></a></li>
        <li><a href="#"><%= t ".special_commercial_code_management" %></a></li>
        <li><%= link_to t(".notifications_management"), notifications_path %></li>
        <li><a href="#"><%= t ".inquiry_management" %></a></li>
        <li><a href="#"><%= t ".inquiry_notifcation_management" %></a></li>
        <li><a href="#"><%= t ".inquiry_reply_template_management" %></a></li>
        <li><a href="#"><%= t ".mail_management" %></a></li>
        <li><a href="#"><%= t ".settlement_report_data" %></a></li>
      </ul>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta charset="utf-8">
    <title><%= Rails.application.class.parent_name %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", media: "all" %>

    <%= yield :specific_page_css %>
    <%= yield :specific_page_js_on_head %>
  </head>

  <body>
    <div id="wrapper">
      <a id="pagetop"></a>
      <%= render "layouts/header" %>
      <%= render "layouts/sidebar" %>
      <main class="mainContents" role="main">
        <article>
          <h2><%= yield :title %></h2>
          <%= yield %>
        </article>
      </main>
      <%= render "layouts/footer" %>
    </div>

    <%= javascript_include_tag "application" %>

    <%= yield :specific_page_js %>
  </body>
</html>

app/views/notifications/edit.html.erb
<% provide(:title, t(".title")) %>

app/views/notifications/index.html.erb
<% provide(:title, t(".title")) %>

app/views/notifications/new.html.erb
<% provide(:title, t(".title")) %>

app/views/services/edit.html.erb
<% provide(:title, t(".title")) %>

app/views/services/index.html.erb
<% provide(:title, t(".title")) %>